program ::= line program | EOF

line ::= LABEL | instruction

instruction ::= CLS
                | RET
                | SYS
                | JP
                | CALL
                | SE
                | SNE
                | LD
                | ADD
                | OR
                | AND
                | XOR
                | SUB
                | SHR
                | SUBN
                | SHL
                | RND
                | DRW
                | SKP
                | SKNP
                | DW

CLS ::= "CLS"
RET ::= "RET"
JP ::= "JP" location
CALL ::= "CALL" location
SE ::= "SE" register literal
SNE ::= "SNE" register literal
